
---
- name: Adding logstash APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present
- name: Update repositories cache and install Logstash
  apt:
    name: logstash
    update_cache: yes
- name: Creates SSL directories
  file:
    path: /etc/pki/tls/certs
    state: directory
- name: Creates SSL directories
  file:
    path: /etc/pki/tls/private
    state: directory
- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/ssl/openssl.cnf
    regexp: 'subjectAltName ='
    line: 'subjectAltName = IP: {{ elk_ip }}'
#- name: Generate SSL certificates
#  shell: "openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"

- name: Configure Logstash public key
  template:
    src=logstash-forwarder.crt
    dest=/etc/pki/tls/certs/logstash-forwarder.crt
    owner=root
    group=root
    mode=0644

- name: Configure Logstash private key
  template:
    src=logstash-forwarder.key
    dest=/etc/pki/tls/private/logstash-forwarder.key
    owner=root
    group=root
    mode=0644

- name: Configure Beats configuration file
  template:
    src=beats-input.conf.j2
    dest=/etc/logstash/conf.d/02-beats-input.conf
    owner=root
    group=root
    mode=0644
- name: Configure Syslog Filter
  template:
    src=syslog-filter.conf.j2
    dest=/etc/logstash/conf.d/10-syslog-filter.conf
    owner=root
    group=root
    mode=0644
- name: Configure Elasticsearch output file
  template:
    src=elasticsearch-output.conf.j2
    dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
    owner=root
    group=root
    mode=0644


- name: Restarting logstash
  service:
    name: logstash
    state: restarted
