---

- name: Adding Kibana APT repository
  apt_repository:
    repo: "deb http://packages.elastic.co/kibana/4.5/debian stable main"
    state: present
- name: Update repositories cache and install Kibana
  apt:
    name: kibana
    update_cache: yes
- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: localhost'

- name: Restarting kibana
  service:
    name: kibana
    state: started
